<!DOCTYPE html>
<html>
<head>
    <title>Station</title>
    <link rel="stylesheet" type="text/css" href="/style.css">
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="/main.js"></script>
</head>
<body>

<section class="error-server-connection-lost text-center hide">Соединение с сервером потеряно, <a href="javascript:window.location.reload();">обновите страницу</a></section>
<div style="height:20px;"></div>